/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.java858.todoapp.gui;

import it.java858.todoapp.gui.model.CategoriaTM;
import it.java858.todoapp.entity.Categoria;
import it.java858.todoapp.service.CategoriaService;
import javax.swing.ListSelectionModel;

/**
 *
 * @author tss
 */
public class CategoriaCRUD extends javax.swing.JDialog {

    CategoriaTM categoriaTM;
       
    /**
     * Creates new form CategoriaCRUD
     */
    public CategoriaCRUD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        categoriaTM=new CategoriaTM(CategoriaService.findAll());
        tblCategorie.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblCategorie.setModel(categoriaTM);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategorie = new javax.swing.JTable();
        cmdModifica = new javax.swing.JButton();
        cmdCancella = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestione Categorie");

        tblCategorie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCategorie);

        cmdModifica.setText("modifica");
        cmdModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdModificaActionPerformed(evt);
            }
        });

        cmdCancella.setText("cancella");
        cmdCancella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancellaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdModifica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdCancella))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdModifica)
                    .addComponent(cmdCancella))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCancellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancellaActionPerformed

        Categoria toRemove=categoriaTM.get
        (tblCategorie.convertRowIndexToModel(tblCategorie.getSelectedRow()));
        CategoriaService.elimina(toRemove);
        categoriaTM.changeData(CategoriaService.findAll());
    }//GEN-LAST:event_cmdCancellaActionPerformed

    private void cmdModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdModificaActionPerformed
        Categoria toEdit = categoriaTM.get
        (tblCategorie.convertRowIndexToModel(tblCategorie.getSelectedRow()));
        CategoriaEdit editView = new CategoriaEdit(toEdit,this,true);
        editView.setLocationRelativeTo(this);
        editView.setVisible(true);
        //tblCategorie.updateUI();
        
    }//GEN-LAST:event_cmdModificaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCancella;
    private javax.swing.JButton cmdModifica;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCategorie;
    // End of variables declaration//GEN-END:variables
}
